name: Deploy Go Application

on:
  push:
    branches:
      - main
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      
      - name: Create .env file
        run: echo "PORT=8080" >> .env
      
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build docker image
        run: docker build -t integrationninjas/go-app .
      
      - name: Push image to docker hub
        run: docker push integrationninjas/go-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull latest image
            docker pull integrationninjas/go-app:latest
            
            # Stop and remove old container
            docker stop go-app-container || true
            docker rm go-app-container || true
            
            # Run new container
            docker run -d -p 8080:8080 --name go-app-container integrationninjas/go-app:latest
            
            # Clean up unused images
            docker image prune -f